[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-test-app (waiting for exactly 3 units, current : 4)
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-test-app/1 [idle] active: received database credentials of the first database
  postgresql-test-app/2 [idle] active: received database credentials of the first database
  postgresql-test-app/3 [idle] active: received database credentials of the first database
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  ubuntu-advantage/1 [idle] active: Attached (esm-apps,esm-infra)
  ubuntu-advantage/3 [idle] active: Attached (esm-apps,esm-infra)
  ubuntu-advantage/5 [idle] active: Attached (esm-apps,esm-infra)
  ubuntu-advantage/6 [idle] active: Attached (esm-apps,esm-infra)
  ubuntu-advantage/7 [idle] active: Attached (esm-apps,esm-infra)
  ubuntu-advantage/8 [idle] active: Attached (esm-apps,esm-infra)
  postgresql-test-app/1 [idle] active: received database credentials of the first database
  postgresql-test-app/2 [idle] active: received database credentials of the first database
  postgresql-test-app/3 [idle] active: received database credentials of the first database
  postgresql/0 [idle] active: 
  postgresql/1 [idle] active: Primary
  postgresql/2 [idle] active: 
  pgbouncer/0 [idle] active: 
  pgbouncer/1 [idle] active: 
  pgbouncer/3 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:937 Model status:

Model    Controller     Cloud/Region         Version  SLA          Timestamp
testing  concierge-lxd  localhost/localhost  3.6.5    unsupported  02:05:42Z

App                  Version  Status   Scale  Charm                Channel      Rev  Exposed  Message
landscape-client              unknown      0  landscape-client     latest/edge   72  no       
pgbouncer            1.21.0   active       3  pgbouncer                           0  no       
postgresql           14.17    active       3  postgresql           14/edge      705  no       
postgresql-test-app           active       3  postgresql-test-app  latest/edge  381  no       received database credentials of the first database
ubuntu-advantage              active       6  ubuntu-advantage     latest/edge  137  no       Attached (esm-apps,esm-infra)

Unit                    Workload  Agent  Machine  Public address  Ports     Message
postgresql-test-app/1*  active    idle   1        10.189.128.4              received database credentials of the first database
  pgbouncer/0*          active    idle            10.189.128.4              
  ubuntu-advantage/1*   active    idle            10.189.128.4              Attached (esm-apps,esm-infra)
postgresql-test-app/2   active    idle   2        10.189.128.129            received database credentials of the first database
  pgbouncer/1           active    idle            10.189.128.129            
  ubuntu-advantage/6    active    idle            10.189.128.129            Attached (esm-apps,esm-infra)
postgresql-test-app/3   active    idle   6        10.189.128.30             received database credentials of the first database
  pgbouncer/3           active    idle            10.189.128.30             
  ubuntu-advantage/8    active    idle            10.189.128.30             Attached (esm-apps,esm-infra)
postgresql/0            active    idle   3        10.189.128.249  5432/tcp  
  ubuntu-advantage/5    active    idle            10.189.128.249            Attached (esm-apps,esm-infra)
postgresql/1*           active    idle   4        10.189.128.252  5432/tcp  Primary
  ubuntu-advantage/3    active    idle            10.189.128.252            Attached (esm-apps,esm-infra)
postgresql/2            active    idle   5        10.189.128.32   5432/tcp  
  ubuntu-advantage/7    active    idle            10.189.128.32             Attached (esm-apps,esm-infra)

Machine  State    Address         Inst id        Base          AZ  Message
1        started  10.189.128.4    juju-ef6300-1  ubuntu@22.04      Running
2        started  10.189.128.129  juju-ef6300-2  ubuntu@22.04      Running
3        started  10.189.128.249  juju-ef6300-3  ubuntu@22.04      Running
4        started  10.189.128.252  juju-ef6300-4  ubuntu@22.04      Running
5        started  10.189.128.32   juju-ef6300-5  ubuntu@22.04      Running
6        started  10.189.128.30   juju-ef6300-6  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:943 Juju error logs:

machine-1: 01:50:05 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:50:05 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-1: 01:50:05 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-0: 01:50:07 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1
machine-4: 01:52:44 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:52:44 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-1: 01:52:44 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-5: 01:53:20 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 01:53:20 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-2: 01:53:20 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:53:32 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:53:32 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-0: 01:53:32 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-1: 01:54:01 ERROR unit.postgresql/1.juju-log Unable to get the state of the cluster
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 493, in _make_request
    conn.request(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 445, in request
    self.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 276, in connect
    self.sock = self._new_conn()
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f29dc8c9de0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.189.128.252', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29dc8c9de0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/src/cluster.py", line 563, in are_replicas_up
    response = requests.get(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.128.252', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29dc8c9de0>: Failed to establish a new connection: [Errno 111] Connection refused'))
machine-2: 01:54:06 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:54:06 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-2: 01:54:06 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-1: 01:54:11 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:54:35 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:54:36 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-0: 01:54:36 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-2: 01:54:41 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-ubuntu-advantage-2: 01:59:49 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-ubuntu-advantage-1: 01:59:49 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-ubuntu-advantage-3: 01:59:49 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-ubuntu-advantage-5: 01:59:49 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-ubuntu-advantage-7: 01:59:49 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-ubuntu-advantage-6: 01:59:54 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-6: 02:02:42 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-6: 02:02:42 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-3: 02:02:42 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-3: 02:02:45 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1
unit-ubuntu-advantage-8: 02:02:45 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 127

[32mINFO    [0m pytest_operator.plugin:plugin.py:1025 Forgetting model main...